# Site settings
title: 左左笑记
header-img: "img/starry.jpg"
tagline: "Eureka！"  
description: "Maris！"  
baseurl: ""
# url: "http://azeril.me"  
# url: "http://localhost:4000"

url: http://zuozuosmiling.com

# enforce_ssl: 

# About/contact
owner: 
  name: "左左"
  email: zht789oo@163.com
  bio: " 登高山 看大海"

# Data

# gavatar: 
favicon: img/favicon.ico
douban_username: 知知知知鸟
github_username: z-flea  
weibo_username: 知知知知鸟
zhihu_username: 知知知知鸟

# Build settings  

# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-paginate
# - jekyll-gallery-generator 
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "左左"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : disqus
  disqus :
      short_name : 左左

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
